server:
  port: ${PORT:8082}

spring:
  application:
    name: microservicios

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: "true"
message:  configuracion custom con sprint cloud config

